In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
em=pd.read_csv('emotions.txt',sep=';',header=None,names=['text','emotion'])

In [3]:
em.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
em.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
em.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     16000 non-null  object
 1   emotion  16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB

In [7]:
unique_em=em['emotion'].unique()

In [8]:
emotions_num={}
i=0
for e in unique_em:
    emotions_num[e]=i
    i+=1
em['emotion']=em['emotion'].map(emotions_num)

In [9]:
emotions_num

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [10]:
em

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [11]:
em['text']=em['text'].apply(lambda x : x.lower())

In [15]:
import string
def rem_pun(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [16]:
em['text']=em['text'].apply(rem_pun)

In [17]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

em['text'] = em['text'].apply(remove_numbers)

In [18]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

em['text'] = em['text'].apply(remove_emojis)