In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ipl_data.csv')
#df.head(2)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1243 non-null   str
 1   season           1243 non-null   str
 2   city             1243 non-null   str
 3   venue            1243 non-null   str
 4   team1            1243 non-null   str
 5   team2            1243 non-null   str
 6   toss_winner      1243 non-null   str
 7   toss_decision    1243 non-null   str
 8   team1_runs       1243 non-null   int64
 9   team1_wickets    1243 non-null   int64
 10  team2_runs       1243 non-null   int64
 11  team2_wickets    1243 non-null   int64
 12  winner           1218 non-null   str
 13  result_type      1243 non-null   str
 14  win_by_runs      1243 non-null   int64
 15  win_by_wickets   1243 non-null   int64
 16  player_of_match  1234 non-null   str
 17  match_referee    1243 non-null   str
 18  umpire1          1243 non-null   str
 19  umpire2          1243 non-null   str
 20  tv_umpire        1243 non-null   str
 21  reserve_umpire   1243 non-null   str
 22  overs_limit      1243 non-null   int64
 23  team1_players    1243 non-null   str
 24  team2_players    1243 non-null   str
 25  year             1243 non-null   int64
dtypes: int64(8), str(18)
memory usage: 807.5 KB

In [4]:
df.describe()

,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit,year
count,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.0,1243.000000
mean,165.851167,5.956557,157.349155,5.873693,13.932422,3.276750,20.0,2017.242156
std,35.490847,2.309341,34.613073,2.646538,23.861556,3.358216,0.0,5.550682
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,2008.000000
25%,144.000000,4.000000,138.000000,4.000000,0.000000,0.000000,20.0,2012.000000
50%,165.000000,6.000000,160.000000,6.000000,0.000000,3.000000,20.0,2017.000000
75%,189.000000,8.000000,179.000000,8.000000,20.000000,6.000000,20.0,2022.000000
max,287.000000,10.000000,265.000000,12.000000,146.000000,10.000000,20.0,2026.000000

In [8]:
print(df['team1_runs'])

0        82
1       207
2       132
3       112
4       165
       ...
1238    203
1239    254
1240    243
1241    214
1242    155
Name: team1_runs, Length: 1243, dtype: int64

In [ ]:
import pandas as pd
df=pd.read_csv(r'D:\python\datasets\area_prices_monthly.csv')

In [3]:
df.head()

,year_month,community,zone,is_freehold,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_secondary,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
0,2020-01,Palm Jumeirah,Palm Jumeirah,True,662,7126,752.0,43,26,72,111,1.5,3.0
1,2020-02,Palm Jumeirah,Palm Jumeirah,True,666,7167,728.0,43,64,78,45,1.5,3.0
2,2020-03,Palm Jumeirah,Palm Jumeirah,True,703,7564,762.0,46,144,71,99,1.5,3.0
3,2020-04,Palm Jumeirah,Palm Jumeirah,True,651,7002,727.0,42,146,69,14,0.4,1.9
4,2020-05,Palm Jumeirah,Palm Jumeirah,True,637,6852,676.0,41,147,28,83,0.4,1.9

In [4]:
df.tail()

,year_month,community,zone,is_freehold,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_secondary,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
6379,2025-12,Jumeirah 3,Jumeirah,True,813,8748,891.0,53,123,13,61,4.0,5.5
6380,2026-01,Jumeirah 3,Jumeirah,True,832,8959,912.0,54,147,21,12,4.0,5.5
6381,2026-02,Jumeirah 3,Jumeirah,True,823,8854,908.0,53,160,77,83,4.0,5.5
6382,2026-03,Jumeirah 3,Jumeirah,True,816,8779,892.0,53,139,9,13,4.0,5.5
6383,2026-04,Jumeirah 3,Jumeirah,True,846,9106,914.0,55,122,10,107,4.0,5.5

In [5]:
print(df)

     year_month      community           zone  is_freehold  \
0       2020-01  Palm Jumeirah  Palm Jumeirah         True
1       2020-02  Palm Jumeirah  Palm Jumeirah         True
2       2020-03  Palm Jumeirah  Palm Jumeirah         True
3       2020-04  Palm Jumeirah  Palm Jumeirah         True
4       2020-05  Palm Jumeirah  Palm Jumeirah         True
...         ...            ...            ...          ...
6379    2025-12     Jumeirah 3       Jumeirah         True
6380    2026-01     Jumeirah 3       Jumeirah         True
6381    2026-02     Jumeirah 3       Jumeirah         True
6382    2026-03     Jumeirah 3       Jumeirah         True
6383    2026-04     Jumeirah 3       Jumeirah         True

      secondary_price_per_sqft_usd  secondary_price_per_m2_usd  \
0                              662                        7126
1                              666                        7167
2                              703                        7564
3                              651                        7002
4                              637                        6852
...                            ...                         ...
6379                           813                        8748
6380                           832                        8959
6381                           823                        8854
6382                           816                        8779
6383                           846                        9106

      offplan_price_per_sqft_usd  rental_price_per_sqft_annual_usd  \
0                          752.0                                43
1                          728.0                                43
2                          762.0                                46
3                          727.0                                42
4                          676.0                                41
...                          ...                               ...
6379                       891.0                                53
6380                       912.0                                54
6381                       908.0                                53
6382                       892.0                                53
6383                       914.0                                55

      n_listings_secondary  n_listings_offplan  n_listings_rental  \
0                       26                  72                111
1                       64                  78                 45
2                      144                  71                 99
3                      146                  69                 14
4                      147                  28                 83
...                    ...                 ...                ...
6379                   123                  13                 61
6380                   147                  21                 12
6381                   160                  77                 83
6382                   139                   9                 13
6383                   122                  10                107

      cbuae_base_rate_pct  avg_mortgage_rate_pct
0                     1.5                    3.0
1                     1.5                    3.0
2                     1.5                    3.0
3                     0.4                    1.9
4                     0.4                    1.9
...                   ...                    ...
6379                  4.0                    5.5
6380                  4.0                    5.5
6381                  4.0                    5.5
6382                  4.0                    5.5
6383                  4.0                    5.5

[6384 rows x 13 columns]

In [7]:
print(df['community'])

0       Palm Jumeirah
1       Palm Jumeirah
2       Palm Jumeirah
3       Palm Jumeirah
4       Palm Jumeirah
            ...
6379       Jumeirah 3
6380       Jumeirah 3
6381       Jumeirah 3
6382       Jumeirah 3
6383       Jumeirah 3
Name: community, Length: 6384, dtype: object

In [20]:
df.drop(columns=['n_listings_secondary'],inplace=True)

In [21]:
print(df.columns)

Index(['year_month', 'community', 'zone', 'secondary_price_per_sqft_usd',
       'secondary_price_per_m2_usd', 'offplan_price_per_sqft_usd',
       'rental_price_per_sqft_annual_usd', 'n_listings_offplan',
       'n_listings_rental', 'cbuae_base_rate_pct', 'avg_mortgage_rate_pct'],
      dtype='object')

In [22]:
df.head()

,year_month,community,zone,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
0,2020-01,Palm Jumeirah,Palm Jumeirah,662,7126,752.0,43,72,111,1.5,3.0
1,2020-02,Palm Jumeirah,Palm Jumeirah,666,7167,728.0,43,78,45,1.5,3.0
2,2020-03,Palm Jumeirah,Palm Jumeirah,703,7564,762.0,46,71,99,1.5,3.0
3,2020-04,Palm Jumeirah,Palm Jumeirah,651,7002,727.0,42,69,14,0.4,1.9
4,2020-05,Palm Jumeirah,Palm Jumeirah,637,6852,676.0,41,28,83,0.4,1.9

In [ ]:
import pandas as pd 
df=pd.read_csv('')