In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ipl_data.csv')
df.head(2)

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
0,2008-04-18,2007/08,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,82,10,...,BB McCullum,J Srinath,Asad Rauf,RE Koertzen,AM Saheba,VN Kulkarni,20,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",2008
1,2008-04-19,2007/08,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MEK Hussey,S Venkataraghavan,MR Benson,SL Shastri,RB Tiffin,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",2008

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1243 non-null   str
 1   season           1243 non-null   str
 2   city             1243 non-null   str
 3   venue            1243 non-null   str
 4   team1            1243 non-null   str
 5   team2            1243 non-null   str
 6   toss_winner      1243 non-null   str
 7   toss_decision    1243 non-null   str
 8   team1_runs       1243 non-null   int64
 9   team1_wickets    1243 non-null   int64
 10  team2_runs       1243 non-null   int64
 11  team2_wickets    1243 non-null   int64
 12  winner           1218 non-null   str
 13  result_type      1243 non-null   str
 14  win_by_runs      1243 non-null   int64
 15  win_by_wickets   1243 non-null   int64
 16  player_of_match  1234 non-null   str
 17  match_referee    1243 non-null   str
 18  umpire1          1243 non-null   str
 19  umpire2          1243 non-null   str
 20  tv_umpire        1243 non-null   str
 21  reserve_umpire   1243 non-null   str
 22  overs_limit      1243 non-null   int64
 23  team1_players    1243 non-null   str
 24  team2_players    1243 non-null   str
 25  year             1243 non-null   int64
dtypes: int64(8), str(18)
memory usage: 807.5 KB

In [5]:
df.describe()

,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit,year
count,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.0,1243.000000
mean,165.851167,5.956557,157.349155,5.873693,13.932422,3.276750,20.0,2017.242156
std,35.490847,2.309341,34.613073,2.646538,23.861556,3.358216,0.0,5.550682
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,2008.000000
25%,144.000000,4.000000,138.000000,4.000000,0.000000,0.000000,20.0,2012.000000
50%,165.000000,6.000000,160.000000,6.000000,0.000000,3.000000,20.0,2017.000000
75%,189.000000,8.000000,179.000000,8.000000,20.000000,6.000000,20.0,2022.000000
max,287.000000,10.000000,265.000000,12.000000,146.000000,10.000000,20.0,2026.000000